GET http://localhost:3001/api/films

###

GET http://localhost:3001/api/films/favorite

###

GET http://localhost:3001/api/films/best

###
GET http://localhost:3001/api/films/last-month

###

GET http://localhost:3001/api/films/unseen

###

GET http://localhost:3001/api/films/4

###

POST http://localhost:3001/api/films
content-type: application/json

{
  "title": "Dune part 1",
  "isFavorite": false,
  "watchDate": null,
  "rating": 3,
  "userId": 1
}

###

PUT http://localhost:3001/api/films/4
content-Type: application/json 

{
  "title": "Matrix",
  "watchDate": null
}

###

PUT http://localhost:3001/api/films/4/rating
content-Type: application/json

{
    "rating": 5
}

###

PUT http://localhost:3001/api/films/4/favorite
content-Type: application/json

{
    "isFavorite": true
}

###

DELETE http://localhost:3001/api/films/7